version: '3.3'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  backend:
    image: senorkotek/foodgram-backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: senorkotek/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static/
      - media:/media
      - redoc:/api/docs/
    depends_on:
      - backend
    restart: always

volumes:
  static_value:
  media_value:
  postgres_data:
  redoc: