version: '3.3'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  backend:
    image: senorkotek/foodgram-backend:latest
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: senorkotek/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  gateway:
    build: senorkotek/foodgram-gateway:latest
    ports:
      - 8000:80
    volumes:
      - static:/static/
      - media:/media
    depends_on:
      - backend
    restart: always

volumes:
  static:
  media:
  pg_data: